### ISSUE TITLE
Don't match stray colons

### ISSUE THREAD

**Issue by markedmondson** [retailzipline/time_range_extractor#3]
`TimeRangeExtractor.call("9:am-10pm")
=> Sun, 30 Jun 2019 00:00:00 UTC +00:00..Sun, 30 Jun 2019 22:00:00 UTC +00:00`

A conditional pattern on the : with a following integer might save a slip.

**Comment by jhubert** [comment]
```
>> TimeRangeExtractor.call("9:am-10pm")
=> nil
```
